---
plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'
  Max: 50

Naming/FileName:
  Exclude:
    - 'lib/github-issues.rb'

RSpec/ExampleLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
